cells: 
  drawio:
    link:
      url: "https://app.diagrams.net/?p=svgdata"
  haproxy:
    link: http://localhost/d/adtzt9ueok0lcf/haproxy?orgId=1&refresh=5s
  mysql:
    link: http://localhost/d/549c2bf8936f7767ea6ac47c47b00f2a/mysql-dasboard?orgId=1&refresh=10s
